let socket,myId=null,myRole=null,room=null,actionDone=false;const $=id=>document.getElementById(id),msg=t=>$("message").textContent=t;
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function emoji(r){return({人狼:"🐺",占い師:"🔮",騎士:"🛡️",霊媒師:"👻",村人:"👤"})[r]||"❓"}
function render(){if(!room||!myRole||room.phase==="finished")return;let me=room.players.find(p=>p.id===myId);if(!me?.alive){$("actionArea").innerHTML="<p>あなたは脱落しています。</p>";return}if(actionDone){$("actionArea").innerHTML="<p>行動済みです。他のプレイヤーを待っています…</p>";return}let ts=room.players.filter(p=>p.alive&&p.id!==myId),h=`<h3>${room.phase==="night"?"夜の行動":"投票"}</h3>`;if(room.phase==="night"){if(!["人狼","占い師","騎士"].includes(myRole)){$("actionArea").innerHTML="<p>夜は待機してください。</p>";return}h+=ts.map(p=>`<button class="target" onclick="night('${p.id}')">${esc(p.name)}</button>`).join("")}else h+=ts.map(p=>`<button class="target" onclick="vote('${p.id}')">🗳️ ${esc(p.name)}に投票</button>`).join("");$("actionArea").innerHTML=h}
function connect(){if(typeof io==="undefined"){msg("通信プログラムを読み込めません。ページを再読み込みしてください。");return}socket=io(window.location.origin,{transports:["websocket","polling"]});socket.on("connect",()=>{myId=socket.id;msg("サーバーに接続しました。")});socket.on("connect_error",e=>msg("サーバー接続エラー: "+e.message));socket.on("room:joined",({code})=>{$("home").classList.add("hidden");$("room").classList.remove("hidden");$("roomCode").textContent=code;msg("ルームに入りました！")});socket.on("room:update",d=>{room=d;$("room").classList.remove("hidden");$("roomCode").textContent=d.code;$("phase").textContent=d.phase==="lobby"?`待機中：${d.players.length}/10人`:d.phase==="night"?`🌙 ${d.day}日目・夜`:d.phase==="day"?`☀️ ${d.day}日目・昼`:"ゲーム終了";$("players").innerHTML=d.players.map(p=>`<div class="player ${p.alive?"":"dead"}"><span>${esc(p.name)}${p.id===myId?"（自分）":""}</span><span>${p.host?"👑":""}${p.alive?"🟢":"⚫"}</span></div>`).join("");let me=d.players.find(p=>p.id===myId);$("start").classList.toggle("hidden",!(me&&me.host&&!d.started));if(d.started)$("game").classList.remove("hidden");$("actionArea").innerHTML=d.phase==="finished"?`<div class="winner">🏆 ${d.winner}の勝利！</div>`:"";if(d.phase!=="finished")render()});socket.on("game:role",d=>{myRole=d.role;actionDone=false;$("game").classList.remove("hidden");$("roleTitle").textContent="あなたの役職";$("roleText").innerHTML=`<div class="role">${emoji(d.role)} ${d.role}</div>`;render()});socket.on("action:result",d=>msg(d.text));socket.on("error:msg",msg)}
connect();
$("create").onclick=()=>{if(!socket?.connected)return msg("サーバーに接続中です。少し待ってください。");socket.emit("room:create",{name:$("name").value})};
$("join").onclick=()=>{if(!socket?.connected)return msg("サーバーに接続中です。少し待ってください。");socket.emit("room:join",{name:$("name").value,code:$("code").value})};
$("start").onclick=()=>socket?.emit("game:start");
window.night=id=>{socket.emit("action:night",{action:myRole==="人狼"?"wolf":myRole==="占い師"?"seer":"guard",targetId:id});actionDone=true;render()};window.vote=id=>{socket.emit("action:vote",{targetId:id});actionDone=true;render()};